package com.palladium.paf.db.membertags.hibernate;

// Generated Jan 23, 2008 10:17:38 PM by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberTagId generated by hbm2java
 */
@Entity
@Table(name = "MEMBER_TAG_ID", schema = "PAFSYS")
public class AnnMemberTagId implements java.io.Serializable {

	private int idInt;

	private int appIdInt;

	private String memberTagNameTxt;

	public AnnMemberTagId() {
	}

	public AnnMemberTagId(int idInt, int appIdInt, String memberTagNameTxt) {
		this.idInt = idInt;
		this.appIdInt = appIdInt;
		this.memberTagNameTxt = memberTagNameTxt;
	}

	@Id
	@Column(name = "ID_INT", unique = true, nullable = false)
	public int getIdInt() {
		return this.idInt;
	}

	public void setIdInt(int idInt) {
		this.idInt = idInt;
	}

	@Column(name = "APP_ID_INT", nullable = false)
	public int getAppIdInt() {
		return this.appIdInt;
	}

	public void setAppIdInt(int appIdInt) {
		this.appIdInt = appIdInt;
	}

	@Column(name = "MEMBER_TAG_NAME_TXT", nullable = false, length = 80)
	public String getMemberTagNameTxt() {
		return this.memberTagNameTxt;
	}

	public void setMemberTagNameTxt(String memberTagNameTxt) {
		this.memberTagNameTxt = memberTagNameTxt;
	}

}
