package com.pace.base.db.membertags.hibernate;

// Generated Jan 23, 2008 10:17:38 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberTagData generated by hbm2java
 */
@Entity
@Table(name = "MEMBER_TAG_DATA", schema = "PAFSYS")
public class AnnMemberTagData implements java.io.Serializable {

	private int idInt;

	private int memberTagIdInt;

	private int memberTagMappingsIdInt;

	private String memberTagValueTxt;

	private int memberTagTypeInt;

	private String creatorTxt;

	private Date lastUpdatedDt;

	public AnnMemberTagData() {
	}

	public AnnMemberTagData(int idInt, int memberTagIdInt,
			int memberTagMappingsIdInt, String memberTagValueTxt,
			int memberTagTypeInt, String creatorTxt, Date lastUpdatedDt) {
		this.idInt = idInt;
		this.memberTagIdInt = memberTagIdInt;
		this.memberTagMappingsIdInt = memberTagMappingsIdInt;
		this.memberTagValueTxt = memberTagValueTxt;
		this.memberTagTypeInt = memberTagTypeInt;
		this.creatorTxt = creatorTxt;
		this.lastUpdatedDt = lastUpdatedDt;
	}

	@Id
	@Column(name = "ID_INT", unique = true, nullable = false)
	public int getIdInt() {
		return this.idInt;
	}

	public void setIdInt(int idInt) {
		this.idInt = idInt;
	}

	@Column(name = "MEMBER_TAG_ID_INT", nullable = false)
	public int getMemberTagIdInt() {
		return this.memberTagIdInt;
	}

	public void setMemberTagIdInt(int memberTagIdInt) {
		this.memberTagIdInt = memberTagIdInt;
	}

	@Column(name = "MEMBER_TAG_MAPPINGS_ID_INT", nullable = false)
	public int getMemberTagMappingsIdInt() {
		return this.memberTagMappingsIdInt;
	}

	public void setMemberTagMappingsIdInt(int memberTagMappingsIdInt) {
		this.memberTagMappingsIdInt = memberTagMappingsIdInt;
	}

	@Column(name = "MEMBER_TAG_VALUE_TXT", nullable = false, length = 1024)
	public String getMemberTagValueTxt() {
		return this.memberTagValueTxt;
	}

	public void setMemberTagValueTxt(String memberTagValueTxt) {
		this.memberTagValueTxt = memberTagValueTxt;
	}

	@Column(name = "MEMBER_TAG_TYPE_INT", nullable = false)
	public int getMemberTagTypeInt() {
		return this.memberTagTypeInt;
	}

	public void setMemberTagTypeInt(int memberTagTypeInt) {
		this.memberTagTypeInt = memberTagTypeInt;
	}

	@Column(name = "CREATOR_TXT", nullable = false)
	public String getCreatorTxt() {
		return this.creatorTxt;
	}

	public void setCreatorTxt(String creatorTxt) {
		this.creatorTxt = creatorTxt;
	}

	@Column(name = "LAST_UPDATED_DT", nullable = false, length = 26)
	public Date getLastUpdatedDt() {
		return this.lastUpdatedDt;
	}

	public void setLastUpdatedDt(Date lastUpdatedDt) {
		this.lastUpdatedDt = lastUpdatedDt;
	}

}
