package com.pace.base.db.membertags.hibernate;

// Generated Jan 23, 2008 10:17:38 PM by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberTagMappings generated by hbm2java
 */
@Entity
@Table(name = "MEMBER_TAG_MAPPINGS", schema = "PAFSYS")
public class AnnMemberTagMappings implements java.io.Serializable {

	private int idInt;

	private int dimensionIdInt;

	private String memberNameTxt;

	private int memberTagMappingsIdInt;

	public AnnMemberTagMappings() {
	}

	public AnnMemberTagMappings(int idInt, int dimensionIdInt,
			String memberNameTxt, int memberTagMappingsIdInt) {
		this.idInt = idInt;
		this.dimensionIdInt = dimensionIdInt;
		this.memberNameTxt = memberNameTxt;
		this.memberTagMappingsIdInt = memberTagMappingsIdInt;
	}

	@Id
	@Column(name = "ID_INT", unique = true, nullable = false)
	public int getIdInt() {
		return this.idInt;
	}

	public void setIdInt(int idInt) {
		this.idInt = idInt;
	}

	@Column(name = "DIMENSION_ID_INT", nullable = false)
	public int getDimensionIdInt() {
		return this.dimensionIdInt;
	}

	public void setDimensionIdInt(int dimensionIdInt) {
		this.dimensionIdInt = dimensionIdInt;
	}

	@Column(name = "MEMBER_NAME_TXT", nullable = false)
	public String getMemberNameTxt() {
		return this.memberNameTxt;
	}

	public void setMemberNameTxt(String memberNameTxt) {
		this.memberNameTxt = memberNameTxt;
	}

	@Column(name = "MEMBER_TAG_MAPPINGS_ID_INT", nullable = false)
	public int getMemberTagMappingsIdInt() {
		return this.memberTagMappingsIdInt;
	}

	public void setMemberTagMappingsIdInt(int memberTagMappingsIdInt) {
		this.memberTagMappingsIdInt = memberTagMappingsIdInt;
	}

}
