package com.palladium.paf.db;



/**
 * SecurityGroups generated by MyEclipse - Hibernate Tools
 */

public class SecurityGroup implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String securityDomainNameTxt;
     private String securityGroupNameTxt;
 	 private Application application;


    // Constructors

    /** default constructor */
    public SecurityGroup() {
    }

	/** minimal constructor */
    public SecurityGroup(Integer id, String securityDomainNameTxt, String securityGroupNameTxt) {
        this.id = id;
        this.securityDomainNameTxt = securityDomainNameTxt;
        this.securityGroupNameTxt = securityGroupNameTxt;
    }
    
    /** full constructor */
    public SecurityGroup(Integer id, String securityDomainNameTxt, String securityGroupNameTxt, Application application) {
        this.id = id;
        this.securityDomainNameTxt = securityDomainNameTxt;
        this.securityGroupNameTxt = securityGroupNameTxt;
        this.application = application;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getSecurityDomainNameTxt() {
        return this.securityDomainNameTxt;
    }
    
    public void setSecurityDomainNameTxt(String securityDomainNameTxt) {
        this.securityDomainNameTxt = securityDomainNameTxt;
    }

    public String getSecurityGroupNameTxt() {
        return this.securityGroupNameTxt;
    }
    
    public void setSecurityGroupNameTxt(String securityGroupNameTxt) {
        this.securityGroupNameTxt = securityGroupNameTxt;
    }

    /**
	 * @return the application
	 */
	public Application getApplication() {
		return application;
	}

	/**
	 * @param application the application to set
	 */
	public void setApplication(Application application) {
		this.application = application;
	}
   








}